load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Load OpentTelemetry-CPP dependency
http_archive(
    name = "io_opentelemetry_cpp",
    sha256 = "34ee951876502a7c1e67ac75ffa65d7c63c63dfbf6175640169411d5f6962fac",
    strip_prefix = "opentelemetry-cpp-1.0.0-rc3",
    urls = [
        "https://github.com/open-telemetry/opentelemetry-cpp/archive/refs/tags/v1.0.0-rc3.tar.gz"
    ],
)

# Load OpenTelemetry dependencies after load.
load("@io_opentelemetry_cpp//bazel:repository.bzl", "opentelemetry_cpp_deps")

opentelemetry_cpp_deps()

# Load gRPC dependencies after load.
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

# Load extra gRPC dependencies due to https://github.com/grpc/grpc/issues/20511
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()
